export enum ERROR_MESSAGE {
  INVALID_INPUT_ERROR = 'Invalid input error',
  INVALID_INPUT_EMAIL_ERROR = 'Invalid input email error',
  EMAIL_IS_IN_USED = 'Email is in used',
  USER_NOT_FOUND = 'User not found',
  USER_PASSWORD_NOT_MATCH = 'User password not found',
  USER_IS_NOT_ACTIVE = 'User is not active',
  ROLE_NOT_FOUND = 'Role not found',
  HTTP_STATUS_ERROR = 'Http status error',
  ROLE_ERROR = 'Role not found'
}

export enum ERROR_CODE {
  INVALID_INPUT_ERROR = 'INVALID_INPUT_ERROR',
  INVALID_INPUT_EMAIL_ERROR = 'INVALID_INPUT_EMAIL_ERROR',
  EMAIL_IS_IN_USED = 'EMAIL_IS_IN_USED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_PASSWORD_NOT_MATCH = 'USER_PASSWORD_NOT_MATCH',
  USER_IS_NOT_ACTIVE = 'USER_IS_NOT_ACTIVE',
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  HTTP_STATUS_ERROR = 'HTTP_STATUS_ERROR',
  ROLE_ERROR = 'ROLE_NOT_FOUND',
  WORKING_TIME_NOT_FOUND = 'WORKING_TIME_NOT_FOUND'
}
